### ISSUE TITLE
Distribute RoundhousE on Docker?

### ISSUE THREAD

**Issue by danrien** [chucknorris/roundhouse#342]
Hi all,

Would it be possible to officially distribute a version of RoundhousE in a .Net core based docker container? I've whipped together a quick version of RoundhousE running in a docker container, but it's probably not the best way to do it:

https://github.com/namehillsoftware/dotnet-core-roundhouse/blob/master/Dockerfile

**Comment by erikbra** [comment]
Interesting option!

What would be the scenarios where this would be better than e.g. installing RoundhousE as a .net core global tool? Would it be in scenarios where .net core is not installed on the build server, but docker is installed?

**Comment by danrien** [comment]
Beyond some of the basic benefits of Docker (repeatable installations and deployment, isolation from other processes), I've found it most useful if you want to use RoundhousE within a larger docker deployment, for example, within a docker compose:

```
  sql-server:
    hostname: sql-server
    image: microsoft/mssql-server-linux:2017-CU8
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=strong(!)Password"
    ports:
      - "${DB_PORT:-2433}:1433"
  roundhouse-deploy:
    image: namehillsoftware/dotnet-core-roundhouse
    depends_on:
      - sql-server
    volumes:
      - "${ROUNDHOUSE_SQL_SCRIPTS_DIR}:/scripts"
    command: [ "-c", "Server=sql-server;Database=MyDb;User Id=SA;Password=strong(!)Password;Connect Timeout=120", "-o", "/output" ]
```
